steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'us.gcr.io/$PROJECT_ID/script-bytes:$COMMIT_SHA'
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'us.gcr.io/$PROJECT_ID/script-bytes:$COMMIT_SHA'
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - deploy
      - 'script-bytes'
      - '--image'
      - 'us.gcr.io/$PROJECT_ID/script-bytes:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
    entrypoint: gcloud
timeout: 1200s
images:
  - 'us.gcr.io/$PROJECT_ID/script-bytes:$COMMIT_SHA'
